# -*- coding: utf-8 -*-
"""
generated clean list of symptom entries to make a dictionary so we can standardize symptoms
"""

import pandas as pd

#read in data
df_ncov19 = pd.read_csv('https://brunods10.s3-us-west-2.amazonaws.com/MIT_COVID/latestdata.csv')

#filter to rows with non-null entires in the 'symptoms' column
is_sym = ~df_ncov19['symptoms'].isna()
symptom_concat = df_ncov19.loc[is_sym]['symptoms'][1:]

#each entry is a comma separated list; concatenate all lists, coerce to lowercase 
symptom_str = ', '.join(symptom_concat)
symptom_str = symptom_str.lower()

#take care of miscellaneous non-standard delimiters, turning them into commas
symptom_str = symptom_str.replace(';',',')
symptom_str = symptom_str.replace(':',',')
symptom_str = symptom_str.replace('and',',')
symptom_str = symptom_str.replace('with',',')

#split back out into list
symptom_list = symptom_str.split(',')

#use set to eliminate duplicates
symptom_list = list(set(symptom_list))

#load into a dataframe 
symptom_df= pd.DataFrame(symptom_list)

# write to file
symptom_df.to_csv('symptoms.csv')

#*****
#using the above file, a dictionary was generated by hand to convert each symptom to one of a standardized set
#*****
